<?php

/**
 * @file
 * Contains islandora_vtt.module.
 */

use Drupal\media\Entity\Media;

/**
 * Implements hook_theme().
 */
function islandora_vtt_theme($existing, $type, $theme, $path) {
  return [
    'vtt_transcript' => [
      'variables' => [],
      'template' => 'vtt-transcript',
      'path' => $path . '/templates',
    ],
  ];
}

/**
 * Implements hook_preprocess_media().
 */
function islandora_vtt_preprocess_media(&$vars) {
  if (!in_array($vars['view_mode'], ['full', 'default_islandora_display'])) {
    return;
  }

  $media = $vars['media'];
  if (empty($media) || !in_array($media->bundle(), ['audio', 'video'])) {
    return;
  }

  $vtt = islandora_vtt_get_vtt($media);
  if (!$vtt) {
    return;
  }

  $vars['content']['vtt'] = [
    '#theme' => 'vtt_transcript',
  ];
  $vars['#attached']['library'][] = 'islandora_vtt/vtt';
  $vars['#attached']['drupalSettings']['vttUrl'] = $vtt->field_media_file->entity->createFileUrl();
  $vars['#attached']['drupalSettings']['vttPlayerType'] = $media->bundle();
}

/**
 * Helper function to get a media's sibling VTT URL.
 */
function islandora_vtt_get_vtt($media) {
  $mid = \Drupal::database()->query("SELECT mid
    FROM {media__field_media_of} mo
    INNER JOIN {media__field_media_use} u ON u.entity_id = mo.entity_id
    INNER JOIN {media_field_data} m ON m.mid = mo.entity_id
    WHERE mo.bundle = 'extracted_text'
      AND field_media_use_target_id = :tid
      AND field_media_of_target_id = :mid", [
        ':mid' => $media->field_media_of->target_id,
        ':tid' => islandora_vtt_extracted_text_tid(),
      ])->fetchField();
  $vtt = $mid ? Media::load($mid) : FALSE;
  return $vtt
    && $vtt->access('view')
    && !is_null($vtt->field_media_file)
    && !$vtt->field_media_file->isEmpty()
    && !is_null($vtt->field_media_file->entity) ? $vtt : FALSE;
}

/**
 * Helper function to get the extracted text term ID.
 */
function islandora_vtt_extracted_text_tid() {
  static $tid = '';
  if ($tid != '') {
    return $tid;
  }

  $tid = \Drupal::database()->query('SELECT tid FROM {taxonomy_term_field_data}
    WHERE name = :name AND vid = :vid', [
      ':vid' => 'islandora_media_use',
      ':name' => 'Extracted Text',
    ])->fetchField();

  return $tid;
}
